### ISSUE TITLE
AccountHash doesn't seems to return a supported value 

### ISSUE THREAD

**Issue by Ebrahim-hamdy** [casper-network/casper-integrations#3]
I have tried to pass public key to CLAccountHash but Doesn't seems to return a supported value 

# Code 

new CLAccountHash(
  CLPublicKey.fromHex(
    activePublicKey
  ).toAccountHash()
)

# Deployed Contract 

https://testnet.cspr.live/deploy/ad4b0aeaf8f6c1c467536d017818b5bb4ea2181ca71f93f61113254dc43a949a

**Comment by hoffmannjan** [comment]
Hi, assuming that `activePublicKey` is storing public key in hex format with algorithm prefix, you just need to do
`CLPublicKey.fromHex(activePublicKey).toAccountHash()`.

**Comment by piotr-dziubecki** [comment]
cc @ipopescu

**Comment by Ebrahim-hamdy** [comment]
Thanks @hoffmannjan 

I already tried it but I got the below error 

Unhandled Rejection (TypeError): t.clType is not a function

**Comment by hoffmannjan** [comment]
@Ebrahim-hamdy could you share your code with me ?

**Comment by Ebrahim-hamdy** [comment]
Am trying to interact with ERC20 contract using Signer imported from casper-js-sdk
here's the code for calling transfer function


  const recipientAccountHash = new CLAccountHash(
    CLPublicKey.fromHex(recipient).toAccountHash()
  );

  const runtimeArgs = RuntimeArgs.fromMap({
    recipient: recipientAccountHash,
    amount: new CLU256(3000000000),
  });

 const contractHashAsByteArray = utils.contractHashToByteArray(contractHash);

  const deployParams = new DeployUtil.DeployParams(keys.publicKey, chainName);
  const standardPayment = DeployUtil.standardPayment(paymentAmount);
  const newStoredContractByHash =
    DeployUtil.ExecutableDeployItem.newStoredContractByHash(
      contractHashAsByteArray,
      entryPoint,
      runtimeArgs
    );

  let deploy: any = DeployUtil.makeDeploy(
    deployParams,
    newStoredContractByHash,
    standardPayment
  );
  
 When I try to pass receipt as an accountHash I got "Unhandled Rejection (TypeError): t.clType is not a function" 
 above error occurred with makeDeploy function

**Comment by hoffmannjan** [comment]
Hi @Ebrahim-hamdy, are you using `contractHashToByteArray` from https://github.com/casper-ecosystem/casper-cep47-js-client/blob/master/src/utils.ts#L76 ? If so, in which format are you providing contract hash to this function?

**Comment by hoffmannjan** [comment]
Hi @Ebrahim-hamdy , could you try to replace `recipientAccountHash`

`const recipientAccountHash = new CLByteArray(CLPublicKey.fromHex(recipientPublicKey).toAccountHash());`.

**Comment by Ebrahim-hamdy** [comment]
Thanks @hoffmannjan 
It worked
